# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42163a04edd786509cbf3f6fc7f67226a9df28047f023bdd64da0161b75febb6cf0daa29b45179cea6c25c235d7310d8d4ad0f4cc28db331f2edd8d6bd49a1b8

test:
  secret_key_base: 28c3f3e5bc8d1497ca5be970d1cf7af10229d91516fc233b5cf561984d5100f4a90b2cf0d3d4fc6e995abb1164f210b97e8b0ac2984a4f3e9fcbf2a38b317b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
